//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBi()
        {
            this.HopDongThietBi = new HashSet<HopDongThietBi>();
            this.LichSuThietBi = new HashSet<LichSuThietBi>();
            this.LinhKienThietBi = new HashSet<LinhKienThietBi>();
        }
    
        public int MaThietBi { get; set; }
        public string MaTaiSan { get; set; }
        public string Ten { get; set; }
        public decimal Gia { get; set; }
        public string Model { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayNhapKho { get; set; }
        public Nullable<System.DateTime> NgayXuatKho { get; set; }
        public int MaDanhMuc { get; set; }
        public Nullable<int> MaNhaCungCap { get; set; }
        public string Serial { get; set; }
        public Nullable<decimal> GiaKhauHao { get; set; }
        public string DonViTinh { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayBaoHanh { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongThietBi> HopDongThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuThietBi> LichSuThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinhKienThietBi> LinhKienThietBi { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
