//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_NguoiSuDung
    {
        public int MaNguoiDung { get; set; }
        public string Ten { get; set; }
        public int MaPhongBan { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> NgaySinh { get; set; }
        public Nullable<int> ThangSinh { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public Nullable<System.DateTime> SinhNhat { get; set; }
    }
}
