//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWSTUONG_NhomTinTuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NEWSTUONG_NhomTinTuong()
        {
            this.NEWSTUONG_TinDinhKem = new HashSet<NEWSTUONG_TinDinhKem>();
            this.NEWSTUONG_BaiViet = new HashSet<NEWSTUONG_BaiViet>();
        }
    
        public int GroupId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfTopics { get; set; }
        public Nullable<int> NumberOfReplies { get; set; }
        public string Status { get; set; }
        public Nullable<bool> AutoApproved { get; set; }
        public Nullable<int> ViewOrder { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdatedUser { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public string LastPost { get; set; }
        public Nullable<int> LastPostId { get; set; }
        public Nullable<int> LastTopicId { get; set; }
        public Nullable<bool> RequireViewPermission { get; set; }
        public Nullable<bool> RequirePostPermission { get; set; }
        public Nullable<bool> AutoSort { get; set; }
        public string EditMyPost { get; set; }
        public Nullable<bool> TopicLastestPostFirst { get; set; }
    
        public virtual NEWS_NguoiSuDung NEWS_NguoiSuDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEWSTUONG_TinDinhKem> NEWSTUONG_TinDinhKem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEWSTUONG_BaiViet> NEWSTUONG_BaiViet { get; set; }
    }
}
