//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFlownode
    {
        public int ID { get; set; }
        public int WorkflowID { get; set; }
        public string VAITRO { get; set; }
        public string CANBO { get; set; }
        public string YEUCAURIENG { get; set; }
        public short LOAIXL { get; set; }
        public string CANBOUQ { get; set; }
        public Nullable<System.DateTime> NGAYUQ { get; set; }
        public Nullable<System.DateTime> HANUQ { get; set; }
        public Nullable<int> CHANXL { get; set; }
    
        public virtual tbWorkflow tbWorkflow { get; set; }
    }
}
