//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLinhvuc
    {
        public string MALV { get; set; }
        public string TENLV { get; set; }
        public string KYHIEU { get; set; }
        public string GHICHU { get; set; }
    }
}
