//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbModule()
        {
            this.tbNhomchucnangs = new HashSet<tbNhomchucnang>();
        }
    
        public int ID { get; set; }
        public string ModuleName { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumOrder { get; set; }
        public string Links { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbNhomchucnang> tbNhomchucnangs { get; set; }
    }
}
