//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNhomchucnang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbNhomchucnang()
        {
            this.tbChucnangs = new HashSet<tbChucnang>();
        }
    
        public int ID { get; set; }
        public int MODULAID { get; set; }
        public string TENNHOM { get; set; }
        public string ICON { get; set; }
        public Nullable<int> THUTU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChucnang> tbChucnangs { get; set; }
        public virtual tbModule tbModule { get; set; }
    }
}
