//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSovanban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSovanban()
        {
            this.tbVanbandens = new HashSet<tbVanbanden>();
        }
    
        public int ID { get; set; }
        public string TENSO { get; set; }
        public string KYHIEU { get; set; }
        public string DONVIID { get; set; }
        public string LOAIVB { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> LOAI { get; set; }
        public Nullable<int> VITRILUU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVanbanden> tbVanbandens { get; set; }
    }
}
