//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVBdenWorkflow
    {
        public int ID { get; set; }
        public Nullable<int> IDVANBANDI { get; set; }
        public Nullable<int> IDVANBANDEN { get; set; }
        public int LOAI { get; set; }
        public int WorkflowID { get; set; }
    
        public virtual tbVanbanden tbVanbanden { get; set; }
        public virtual tbWorkflow tbWorkflow { get; set; }
    }
}
