//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVBdenCanbo
    {
        public int ID { get; set; }
        public int IDVANBAN { get; set; }
        public string CANBO { get; set; }
        public Nullable<System.DateTime> NGAYMO { get; set; }
    
        public virtual tbVanbanden tbVanbanden { get; set; }
    }
}
