//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbWorkflow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbWorkflow()
        {
            this.tbFilecongvans = new HashSet<tbFilecongvan>();
            this.tbFlownodes = new HashSet<tbFlownode>();
            this.tbVBdenWorkflows = new HashSet<tbVBdenWorkflow>();
            this.tbYkienxulies = new HashSet<tbYkienxuly>();
        }
    
        public int ID { get; set; }
        public string MACV { get; set; }
        public string TENCV { get; set; }
        public string MOTACV { get; set; }
        public string GHICHU { get; set; }
        public short LOAICV { get; set; }
        public int TRANGTHAI { get; set; }
        public string NGUOITAO { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public Nullable<System.DateTime> THOIHAN { get; set; }
        public string MADONVI { get; set; }
        public string BOPHAN { get; set; }
        public Nullable<int> VANBANID { get; set; }
        public Nullable<bool> KHOAXL { get; set; }
        public string KETQUAXL { get; set; }
        public Nullable<System.DateTime> NGAYHOANTHANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFilecongvan> tbFilecongvans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFlownode> tbFlownodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVBdenWorkflow> tbVBdenWorkflows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbYkienxuly> tbYkienxulies { get; set; }
    }
}
