//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbYkienxuly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbYkienxuly()
        {
            this.tbFilexulies = new HashSet<tbFilexuly>();
        }
    
        public int ID { get; set; }
        public int WorkflowID { get; set; }
        public string CANBO { get; set; }
        public System.DateTime NGAYXL { get; set; }
        public string YKIENXL { get; set; }
        public short TRANGTHAI { get; set; }
        public short LOAIXL { get; set; }
        public bool CONGKHAI { get; set; }
        public Nullable<int> PARENTID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFilexuly> tbFilexulies { get; set; }
        public virtual tbWorkflow tbWorkflow { get; set; }
    }
}
